spots:
  brouwersdam:
    url: https://nl.windfinder.com/weatherforecast/brouwersdam
    emails:
      - je.vanderelst@gmail.com
    min_hours: 3
    windspeed_between: [12, 25]
    hours_between: [8, 20]
    temperature_above: 15

  knokke-heist:
    url: https://nl.windfinder.com/weatherforecast/knokke-heist
    emails:
      - je.vanderelst@gmail.com
    min_hours: 3
    windspeed_between: [12, 25]
    hours_between: [8, 20]
    temperature_above: 15

  oesterdam:
    url: https://nl.windfinder.com/weatherforecast/oosterschelde_oesterdam
    emails:
      - je.vanderelst@gmail.com
    min_hours: 3
    windspeed_between: [12, 25]
    hours_between: [8, 20]
    temperature_above: 15

